function config = defaultConfig()
%DEFAULTCONFIG Return a render configuration preserving M3.0 output.
    typography = struct( ...
        'basePt', [], ...
        'axesLabelPt', [], ...
        'titlePt', [], ...
        'tickLabelPt', [], ...
        'legendPt', [], ...
        'colorbarLabelPt', [], ...
        'colorbarTickLabelPt', []);
    config = struct('standaloneBorderPt', 2, 'typography', typography);
end
