function lines = renderImage(node, colormapName, colorMapping)
%RENDERIMAGE Serialize scalar cells as a deterministic PGFPlots matrix plot.
    if ~strcmp(node.colorMode, 'scalar') || ~strcmp(node.alphaMode, 'opaque')
        error('M2T2:E053:UnsupportedVectorRichImage', ...
              'M2T2:E053:UnsupportedVectorRichImage: RGB and alpha require hybrid');
    end
    bs = char(92);
    if numel(node.x)<2||numel(node.y)<2
        error('M2T2:E054:UnsupportedImageCoordinates', ...
            'M2T2-E054 UnsupportedImageCoordinates: vector matrix plots require at least two rows and columns; select hybrid explicitly.');
    end
    options = {'matrix plot*', ...
               ['mesh/cols=' num2str(numel(node.x))], ...
               'point meta=explicit', ...
               'colormap access=direct', ...
               ['colormap name=' colormapName], ...
               'forget plot'};
    lines=cell(1,numel(node.y)+3);
    lines(1:2) = {[bs 'addplot[' m2t2.util.joinCell(options, ',') '] table[meta=c] {'], ...
             'x y value c'};
    indices = m2t2.render.imageColorIndices(node.cdata, colorMapping, ...
                                            node.mapping, node.directIndexBase);
    for row = 1:numel(node.y)
        % One bounded source row per buffer; preserve exact row/column order.
        % Concatenating integer CData with doubles can coerce coordinates to
        % integers in MATLAB. Match scalar %g conversion explicitly instead.
        values=[double(reshape(node.x,1,[]));repmat(double(node.y(row)),1,numel(node.x)); ...
            double(node.cdata(row,:));double(indices(row,:))];
        lines{row+2}=m2t2.render.formatNumericRows(values);
    end
    lines{end} = '};';
end
