function lines = renderHybridImage(assetReference, xExtent, yExtent)
%RENDERHYBRIDIMAGE Place a pixel-exact image layer in scientific coordinates.
    bs = char(92);
    options = { ...
        ['xmin=' m2t2.util.formatNumber(xExtent(1))], ...
        ['xmax=' m2t2.util.formatNumber(xExtent(2))], ...
        ['ymin=' m2t2.util.formatNumber(yExtent(1))], ...
        ['ymax=' m2t2.util.formatNumber(yExtent(2))], ...
        '/pgfplots/forget plot'};
    lines = {[bs 'addplot graphics[' m2t2.util.joinCell(options, ',') ...
             '] {' assetReference '};']};
end
