function series = makeErrorbarSeries()
%MAKEERRORBARSERIES Construct a normalized 2-D errorbar node.
    series = struct( ...
        'kind', 'm2t2.errorbar', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'x', zeros(1, 0), ...
        'y', zeros(1, 0), ...
        'xNegative', zeros(1, 0), ...
        'xPositive', zeros(1, 0), ...
        'yNegative', zeros(1, 0), ...
        'yPositive', zeros(1, 0), ...
        'color', [0 0 1], ...
        'width', 0.5, ...
        'style', 'solid', ...
        'marker', 'none', ...
        'markerSize', 6);
end
