function series = makeBarSeries()
%MAKEBARSERIES Construct a vertical grouped-bar semantic series.
    series = struct( ...
        'kind', 'm2t2.bar', ...
        'id', 'axes-1-series-1', ...
        'owner', m2t2.ir.makeOwner('axes', 'axes-1'), ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'orientation', 'vertical', ...
        'mode', 'grouped', ...
        'groupId', 'axes-1-bar-group-1', ...
        'groupIndex', 1, ...
        'groupCount', 1, ...
        'categories', zeros(1, 0), ...
        'values', zeros(1, 0), ...
        'barWidth', 0.8, ...
        'baseline', 0, ...
        'faceVisible', true, ...
        'faceColor', [0 0 1], ...
        'edgeVisible', true, ...
        'edgeColor', [0 0 0], ...
        'lineWidth', 0.5, ...
        'lineStyle', 'solid');
end
