function legendNode = makeLegend()
%MAKELEGEND Construct the normalized legend contract.
    legendNode = struct('visible', false, ...
                        'mode', 'automatic', ...
                        'entries', {{}}, ...
                        'location', 'north_east');
end
