function node = makeColorbar()
%MAKECOLORBAR Construct an explicit figure-level colorbar display node.
    node = struct( ...
        'kind', 'm2t2.colorbar', ...
        'id', 'colorbar-1', ...
        'owner', m2t2.ir.makeOwner('axes', 'axes-1'), ...
        'associatedAxesIds', {{'axes-1'}}, ...
        'orientation', 'vertical', ...
        'placement', m2t2.ir.makePlacement(0.88, 0.1, 0.04, 0.8), ...
        'location', 'eastoutside', ...
        'direction', 'normal', ...
        'scale', 'linear', ...
        'limits', [0 1], ...
        'ticks', m2t2.ir.makeTickSpec(), ...
        'label', m2t2.ir.makeText());
end
