function node = makeSharedLabel(role, text)
%MAKESHAREDLABEL Construct a figure/layout-owned semantic label.
    if nargin < 1, role = 'title'; end
    if nargin < 2, text = m2t2.ir.makeText(); end
    node = struct( ...
        'kind', 'm2t2.sharedlabel', ...
        'id', ['shared-' role '-1'], ...
        'owner', m2t2.ir.makeOwner(), ...
        'role', role, ...
        'text', text, ...
        'placement', zeros(1, 0));
end
