function series = makeScatterSeries()
%MAKESCATTERSERIES Construct a normalized rich 2-D scatter node.
    series = struct( ...
        'kind', 'm2t2.scatter', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'x', zeros(1, 0), ...
        'y', zeros(1, 0), ...
        'color', [0 0 1], ...
        'colorMode', 'constant_rgb', ...
        'colorData', zeros(0, 3), ...
        'marker', 'circle', ...
        'sizeMode', 'constant', ...
        'markerSize', 6, ...
        'edgeMode', 'constant', ...
        'edgeColor', [0 0 1], ...
        'faceMode', 'none', ...
        'faceColor', [0 0 1]);
end
