function node = makeSharedLegend()
%MAKESHAREDLEGEND Construct a figure/layout-owned multi-axes legend.
    node = struct( ...
        'kind', 'm2t2.legend', ...
        'id', 'legend-1', ...
        'owner', m2t2.ir.makeOwner(), ...
        'entries', {{}}, ...
        'placement', m2t2.ir.makePlacement(0.25, 0.02, 0.5, 0.08), ...
        'location', 'south');
end
