function series = makeBoxplotSeries()
%MAKEBOXPLOTSERIES Construct a vertical semantic boxplot series.
    series = struct( ...
        'kind','m2t2.boxplot', ...
        'id','axes-1-series-1', ...
        'owner',m2t2.ir.makeOwner('axes','axes-1'), ...
        'displayName',m2t2.ir.makeText(), ...
        'visible',true, ...
        'orientation','vertical', ...
        'positions',zeros(1,0), ...
        'lowerWhisker',zeros(1,0), ...
        'q1',zeros(1,0), ...
        'median',zeros(1,0), ...
        'q3',zeros(1,0), ...
        'upperWhisker',zeros(1,0), ...
        'outlierPositions',zeros(1,0), ...
        'outlierValues',zeros(1,0), ...
        'boxWidth',0.5, ...
        'boxColor',[0 0 1], ...
        'boxLineWidth',4, ...
        'medianColor',[0 0 0], ...
        'medianLineWidth',0.5, ...
        'medianLineStyle','solid', ...
        'whiskerColor',[0 0 0], ...
        'whiskerLineWidth',0.5, ...
        'whiskerLineStyle','solid', ...
        'outlierMarker','x', ...
        'outlierMarkerSize',2, ...
        'outlierColor',[0 0 0]);
end
