function node = makeImageSeries()
%MAKEIMAGESERIES Construct a normalized scalar or truecolor image IR node.
    node = struct( ...
        'kind', 'm2t2.image', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'x', zeros(1, 0), ...
        'y', zeros(1, 0), ...
        'cdata', zeros(0, 0), ...
        'colorMode', 'scalar', ...
        'mapping', 'scaled', ...
        'directIndexBase', 1, ...
        'alphaMode', 'opaque', ...
        'alphaData', 1, ...
        'interpolation', 'nearest');
end
