function node = makeArrowAnnotation(annotationKind)
%MAKEARROWANNOTATION Construct a figure-owned normalized 2-D arrow.
    if nargin < 1, annotationKind = 'arrow'; end
    node = struct( ...
        'kind', 'm2t2.arrowannotation', ...
        'id', 'figure-annotation-1', ...
        'owner', m2t2.ir.makeOwner('figure', 'figure'), ...
        'annotationKind', annotationKind, ...
        'coordinateSpace', 'figure_normalized', ...
        'start', [0 0], ...
        'end', [1 1], ...
        'style', 'solid', ...
        'width', 0.5, ...
        'color', [0 0 0], ...
        'startHead', m2t2.ir.makeArrowHead(), ...
        'endHead', m2t2.ir.makeArrowHead('vback2', 10, 10), ...
        'visible', true);
end
