function series = makeSurfaceSeries()
%MAKESURFACESERIES Construct the narrow scalar-colored 3-D surface IR.
    series = struct( ...
        'kind', 'm2t2.surface', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'x', zeros(0, 0), ...
        'y', zeros(0, 0), ...
        'z', zeros(0, 0), ...
        'c', zeros(0, 0), ...
        'mapping', 'scaled', ...
        'faceMode', 'interpolated', ...
        'edgeMode', 'none');
end
