function series = makeLine3Series()
%MAKELINE3SERIES Construct a normalized semantic Plot3 line.
    series = struct( ...
        'kind', 'm2t2.line3', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'x', zeros(1, 0), ...
        'y', zeros(1, 0), ...
        'z', zeros(1, 0), ...
        'color', [0 0 1], ...
        'width', 0.5, ...
        'style', 'solid', ...
        'marker', 'none', ...
        'markerSize', 6);
end
