function series = makeLineSeries()
%MAKELINESERIES Construct a normalized line-series IR node.
    series = struct( ...
        'kind', 'm2t2.line', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'x', zeros(1, 0), ...
        'y', zeros(1, 0), ...
        'color', [0 0 1], ...
        'width', 0.5, ...
        'style', 'solid', ...
        'marker', 'none', ...
        'markerSize', 6);
end
