function series = makePatch3Series()
%MAKEPATCH3SERIES Construct the narrow opaque triangular Fill3 IR.
    series = struct( ...
        'kind', 'm2t2.patch3', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'vertices', zeros(0, 3), ...
        'faceColor', [0 0 0], ...
        'edgeColor', [0 0 0], ...
        'edgeVisible', true, ...
        'lineWidth', 0.5, ...
        'lineStyle', 'solid');
end
