function series = makeScatterSeries()
%MAKESCATTERSERIES Construct a normalized constant-style scatter node.
    series = struct( ...
        'kind', 'm2t2.scatter', ...
        'id', 'series-1', ...
        'displayName', m2t2.ir.makeText(), ...
        'visible', true, ...
        'x', zeros(1, 0), ...
        'y', zeros(1, 0), ...
        'color', [0 0 1], ...
        'marker', 'circle', ...
        'markerSize', 6);
end
