function axesNode = makeAxes()
%MAKEAXES Construct a normalized 2-D axes IR node with deterministic defaults.
    axesNode = struct( ...
        'kind', 'm2t2.axes2d', ...
        'dimensionality', 2, ...
        'id', 'axes-1', ...
        'placement', m2t2.ir.makePlacement(), ...
        'overlayOf', '', ...
        'xlim', [0 1], ...
        'ylim', [0 1], ...
        'zlim', [0 1], ...
        'xscale', 'linear', ...
        'yscale', 'linear', ...
        'zscale', 'linear', ...
        'xdirection', 'normal', ...
        'ydirection', 'normal', ...
        'zdirection', 'normal', ...
        'view', [0 90], ...
        'projection', 'orthographic', ...
        'dataAspectRatio', [1 1 1], ...
        'plotBoxAspectRatio', [1 1 1], ...
        'box', 'on', ...
        'colorMapping', m2t2.ir.makeColorMapping(), ...
        'xticks', m2t2.ir.makeTickSpec(), ...
        'yticks', m2t2.ir.makeTickSpec(), ...
        'zticks', m2t2.ir.makeTickSpec(), ...
        'xlabel', m2t2.ir.makeText(), ...
        'ylabel', m2t2.ir.makeText(), ...
        'zlabel', m2t2.ir.makeText(), ...
        'title', m2t2.ir.makeText(), ...
        'xgrid', false, ...
        'ygrid', false, ...
        'zgrid', false, ...
        'legend', m2t2.ir.makeLegend(), ...
        'series', {{}});
end
