function node = makeTextAnnotation()
%MAKETEXTANNOTATION Construct an axes-owned 2-D user-text annotation.
    node = struct( ...
        'kind', 'm2t2.textannotation', ...
        'id', 'axes-1-annotation-1', ...
        'owner', m2t2.ir.makeOwner('axes', 'axes-1'), ...
        'coordinateSpace', 'axes_data', ...
        'position', [0 0], ...
        'text', m2t2.ir.makeText(), ...
        'horizontalAlignment', 'left', ...
        'verticalAlignment', 'middle', ...
        'rotation', 0, ...
        'fontSize', 10, ...
        'fontWeight', 'normal', ...
        'fontAngle', 'normal', ...
        'color', [0 0 0], ...
        'visible', true);
end
