function summary = runM61RichScatterTests(outputDirectory)
%RUNM61RICHSCATTERTESTS Validate explicit rich 2-D scatter semantics.
    root=fileparts(fileparts(mfilename('fullpath')));addpath(fullfile(root,'src'));
    if nargin<1,outputDirectory=fullfile(root,'.audit','m61-rich-scatter');end
    if exist(outputDirectory,'dir')~=7,mkdir(outputDirectory);end
    cases={ ...
        'S01_constant_size_constant_rgb',@constantRgb; ...
        'S02_varying_sizes',@varyingSizes; ...
        'S03_per_point_rgb',@perPointRgb; ...
        'S04_scalar_mapped',@scalarMapped; ...
        'S05_scalar_colorbar',@scalarColorbar; ...
        'S06_varying_size_scalar',@varyingScalar; ...
        'S07_varying_size_rgb',@varyingRgb; ...
        'S08_legend_display_name',@legendCase; ...
        'S09_reverse_log_axes',@reverseLog; ...
        'S10_multiple_scatter',@multipleScatter; ...
        'S11_scatter_line',@scatterLine; ...
        'S12_scatter_image_shared_mapping',@scatterImage; ...
        'S13_edge_face_semantics',@edgeFace; ...
        'S14_visibility',@visibilityCase; ...
        'N01_scatter3',@rejectScatter3; ...
        'N02_nonfinite_coordinates',@rejectCoordinates; ...
        'N03_alpha',@rejectAlpha; ...
        'N04_edge_face_mode',@rejectEdgeMode; ...
        'N05_size_shape',@rejectSize; ...
        'N06_color_shape',@rejectColor; ...
        'N07_ir_dimensionality',@rejectIrCoordinates; ...
        'N08_color_scale',@rejectColorScale; ...
        'J01_json_replay_modes',@jsonReplay; ...
        'J02_old_v2_scatter',@oldV2; ...
        'D01_determinism',@determinism; ...
        'L01_figure_lifecycle',@lifecycle; ...
        'P01_publication_85',@()profileWidth('single-column'); ...
        'P02_publication_170',@()profileWidth('double-column'); ...
        'X01_10k_scale',@scaleCase};
    rows=cell(size(cases,1),4);failures=0;
    for k=1:size(cases,1)
        try,detail=cases{k,2}();status='PASS';
        catch err,status='FAIL';failures=failures+1;detail=[identifier(err) ': ' oneLine(err.message)];end
        rows(k,:)={cases{k,1},status,detail,'m6.1'};
    end
    resultPath=fullfile(outputDirectory,'m61-rich-scatter-results.tsv');writeRows(resultPath,rows);
    summary=struct('tests',size(rows,1),'failures',failures,'resultPath',resultPath);
    if failures,fprintf(2,'%s',fileread(resultPath));error('M2T:M61RichScatterTestsFailed','%d M6.1 tests failed.',failures);end

    function d=constantRgb(),[f,~,c]=figureWithScatter(36,[.2 .4 .8],{});s=readSeries(f);assert(strcmp(s.sizeMode,'constant')&&strcmp(s.colorMode,'constant_rgb')&&s.markerSize==6);d='constant marker area and RGB preserved';clear c;end
    function d=varyingSizes(),[f,~,c]=figureWithScatter([16 36 100],[.2 .4 .8],{});s=readSeries(f);assert(strcmp(s.sizeMode,'per_point')&&isequal(s.markerSize,[4 6 10]));d='SizeData area converted to diameter by sqrt';clear c;end
    function d=perPointRgb(),[f,~,c]=figureWithScatter(36,[1 0 0;0 1 0;0 0 1],{});s=readSeries(f);assert(strcmp(s.colorMode,'per_point_rgb')&&isequal(s.colorData,[1 0 0;0 1 0;0 0 1]));d='N-by-3 RGB preserved';clear c;end
    function d=scalarMapped(),[f,a,c]=figureWithScatter(36,[10;20;30],{});caxis(a,[0 40]);s=readSeries(f);ir=m2t2.reader.readFigure(f);assert(strcmp(s.colorMode,'scalar_mapped')&&isequal(s.colorData,[10 20 30])&&isequal(ir.axes{1}.colorMapping.limits,[0 40]));d='scalar point meta and CLim preserved';clear c;end
    function d=scalarColorbar(),[f,a,c]=figureWithScatter(36,[10;20;30],{'filled'});caxis(a,[0 40]);cb=colorbar(a);ylabel(cb,'response');ir=m2t2.reader.readFigure(f);element=ir.elements{1};assert(numel(ir.elements)==1&&strcmp(element.kind,'m2t2.colorbar')&&isequal(element.limits,[0 40])&&strcmp(element.label.value,'response')&&strcmp(element.orientation,'vertical'));d='scalar scatter preserves ColorbarIR limits, label, and orientation';clear c;end
    function d=varyingScalar(),[f,~,c]=figureWithScatter([16 36 100],[10;20;30],{'filled'});s=readSeries(f);assert(strcmp(s.sizeMode,'per_point')&&strcmp(s.colorMode,'scalar_mapped'));writeTex('varying-scalar',f);d='varying diameter plus scalar metadata';clear c;end
    function d=varyingRgb(),[f,~,c]=figureWithScatter([16 36 100],[1 0 0;0 1 0;0 0 1],{'filled'});s=readSeries(f);assert(strcmp(s.sizeMode,'per_point')&&strcmp(s.colorMode,'per_point_rgb'));writeTex('varying-rgb',f);d='varying diameter plus explicit RGB';clear c;end
    function d=legendCase(),[f,a,c]=figureWithScatter(36,[.2 .4 .8],{'DisplayName','Measurements'});legend(a,'show');ir=m2t2.reader.readFigure(f);assert(ir.axes{1}.legend.visible&&strcmp(ir.axes{1}.legend.entries{1}.text.value,'Measurements'));d='DisplayName and legend ownership preserved';clear c;end
    function d=reverseLog(),[f,a,c]=figureWithScatter(36,[.2 .4 .8],{});set(a,'XScale','log','YDir','reverse');set(findobj(a,'Type','scatter'),'XData',[1 10 100]);ir=m2t2.reader.readFigure(f);assert(strcmp(ir.axes{1}.xscale,'log')&&strcmp(ir.axes{1}.ydirection,'reverse'));d='axes transforms remain axes semantics';clear c;end
    function d=multipleScatter(),f=figure('Visible','off');c=onCleanup(@()closeFigure(f));a=axes('Parent',f);hold(a,'on');scatter(a,1:3,[1 2 3],36,[1 0 0]);scatter(a,1:3,[3 2 1],64,[0 0 1]);ir=m2t2.reader.readFigure(f);assert(numel(ir.axes{1}.series)==2);d='series order preserved';clear c;end
    function d=scatterLine(),[f,a,c]=figureWithScatter(36,[.2 .4 .8],{});hold(a,'on');plot(a,1:3,[3 2 1]);ir=m2t2.reader.readFigure(f);assert(numel(ir.axes{1}.series)==2);d='scatter and line coexist';clear c;end
    function d=scatterImage(),f=figure('Visible','off');c=onCleanup(@()closeFigure(f));a=axes('Parent',f);imagesc(a,[1 2;3 4]);hold(a,'on');scatter(a,[1 2],[1 2],36,[1;4],'filled');caxis(a,[0 5]);colorbar(a);ir=m2t2.reader.readFigure(f);assert(numel(ir.axes{1}.series)==2&&numel(ir.elements)==1);tex=m2t2.render.renderPgfplots(ir,true);assert(has(tex,'point meta min=0')&&has(tex,'colormap name='));d='image and scatter share axes color mapping';clear c;end
    function d=edgeFace(),[f,~,c]=figureWithScatter(36,[1 0 0;0 1 0;0 0 1],{'filled','MarkerEdgeColor',[.1 .1 .1]});s=readSeries(f);assert(strcmp(s.edgeMode,'constant')&&strcmp(s.faceMode,'data')&&isequal(s.edgeColor,[.1 .1 .1]));d='constant edge and data-driven filled face preserved';clear c;end
    function d=visibilityCase(),[f,~,c]=figureWithScatter(36,[.2 .4 .8],{'Visible','off'});assert(~readSeries(f).visible);d='series visibility preserved';clear c;end
    function d=rejectScatter3(),f=figure('Visible','off');c=onCleanup(@()closeFigure(f));scatter3(1:3,1:3,1:3);expect(@()m2t2.reader.readFigure(f),'M2T2:E045:UnsupportedScatterDimensionality');d='scatter3 rejected precisely';clear c;end
    function d=rejectCoordinates(),[f,~,c,h]=figureWithScatter(36,[.2 .4 .8],{});set(h,'XData',[1 NaN 3]);expect(@()m2t2.reader.readFigure(f),'M2T2:E040:MalformedScatterData');d='nonfinite coordinates rejected';clear c;end
    function d=rejectAlpha(),[f,~,c,h]=figureWithScatter(36,[.2 .4 .8],{});try,set(h,'MarkerEdgeAlpha',.5);catch,d='runtime exposes no marker-alpha capability; alpha input is not constructible';clear c;return;end;expect(@()m2t2.reader.readFigure(f),'M2T2:E043:UnsupportedScatterTransparency');d='nonopaque marker alpha rejected';clear c;end
    function d=rejectEdgeMode(),[f,~,c,h]=figureWithScatter(36,[.2 .4 .8],{});set(h,'MarkerFaceColor','auto');expect(@()m2t2.reader.readFigure(f),'M2T2:E044:UnsupportedScatterMarkerStyle');d='unsupported automatic face mode rejected';clear c;end
    function d=rejectSize(),[f,~,c,h]=figureWithScatter(36,[.2 .4 .8],{});if strcmp(get(h,'Type'),'hggroup'),ir=scatterIr('constant_rgb','per_point');ir.axes{1}.series{1}.markerSize=[2 3];expect(@()m2t2.ir.validate(ir),'M2T2:E003:InvalidIR');d='gnuplot rejects malformed SizeData during mutation; normalized cardinality is rejected';clear c;return;end;set(h,'SizeData',[2 3]);expect(@()m2t2.reader.readFigure(f),'M2T2:E041:UnsupportedScatterSize');d='malformed SizeData cardinality rejected precisely';clear c;end
    function d=rejectColor(),[f,~,c,h]=figureWithScatter(36,[1 0 0;0 1 0;0 0 1],{'filled'});set(h,'CData',[2 0 0;0 1 0;0 0 1]);expect(@()m2t2.reader.readFigure(f),'M2T2:E042:UnsupportedScatterColor');d='out-of-range active RGB CData rejected precisely';clear c;end
    function d=rejectIrCoordinates(),ir=scatterIr('constant_rgb','constant');ir.axes{1}.series{1}.x(2)=Inf;expect(@()m2t2.ir.validate(ir),'M2T2:E003:InvalidIR');d='invalid normalized coordinates rejected';end
    function d=rejectColorScale(),[f,a,c]=figureWithScatter(36,[10;20;30],{'filled'});try,set(a,'ColorScale','log');catch,d='runtime has no nonlinear ColorScale capability';clear c;return;end;expect(@()m2t2.reader.readFigure(f),'M2T2:E046:UnsupportedScatterColorMapping');d='nonlinear scalar mapping rejected precisely';clear c;end
    function d=jsonReplay(),modes={{'constant_rgb','constant'},{'constant_rgb','per_point'},{'per_point_rgb','constant'},{'per_point_rgb','per_point'},{'scalar_mapped','constant'},{'scalar_mapped','per_point'}};for q=1:numel(modes),ir=scatterIr(modes{q}{1},modes{q}{2});a=m2t2.render.renderPgfplots(ir,true);b=m2t2.render.renderPgfplots(m2t2.ir.fromJson(jsonencode(ir)),true);assert(strcmp(a,b));end;d='six explicit size/color mode combinations replay byte-identically';end
    function d=oldV2(),ir=scatterIr('constant_rgb','constant');s=ir.axes{1}.series{1};s=rmfield(s,{'colorMode','colorData','sizeMode','edgeMode','edgeColor','faceMode','faceColor'});ir.axes{1}.series={s};decoded=m2t2.ir.fromJson(jsonencode(ir));assert(strcmp(decoded.axes{1}.series{1}.colorMode,'constant_rgb'));d='pre-M6.1 v2 scatter defaults remain readable';end
    function d=determinism(),ir=scatterIr('per_point_rgb','per_point');j1=jsonencode(ir);j2=jsonencode(ir);t1=m2t2.render.renderPgfplots(ir,true);t2=m2t2.render.renderPgfplots(ir,true);assert(strcmp(j1,j2)&&strcmp(t1,t2));d='IR JSON, point order, color order, size order, and TeX stable';end
    function d=lifecycle(),[f,a,c,h]=figureWithScatter([16 36 100],[10;20;30],{'filled','DisplayName','Stable'});cb=colorbar(a);before={get(h,'XData'),get(h,'YData'),get(h,'SizeData'),get(h,'CData'),get(h,'Marker'),get(h,'MarkerEdgeColor'),get(h,'MarkerFaceColor'),get(a,'CLim'),colormap(a),get(cb,'Visible'),get(h,'Visible'),get(a,'XLim'),get(f,'Visible')};m2t2.reader.readFigure(f);after={get(h,'XData'),get(h,'YData'),get(h,'SizeData'),get(h,'CData'),get(h,'Marker'),get(h,'MarkerEdgeColor'),get(h,'MarkerFaceColor'),get(a,'CLim'),colormap(a),get(cb,'Visible'),get(h,'Visible'),get(a,'XLim'),get(f,'Visible')};assert(isequaln(before,after));d='reader leaves caller scatter, axes, colormap, colorbar, and figure unchanged';clear c;end
    function d=profileWidth(width),ir=scatterIr('scalar_mapped','per_point');before=ir.axes{1}.series{1}.markerSize;t=m2t.profile.apply(ir,m2t.profile.publication(),width);assert(t.success&&isequal(t.ir.axes{1}.series{1}.markerSize,before));d=[width ' preserves relative marker sizes'];end
    function d=scaleCase(),n=10000;ir=scatterIr('scalar_mapped','constant');s=ir.axes{1}.series{1};s.x=linspace(0,100,n);s.y=sin(s.x/5);s.colorData=cos(s.x/11);ir.axes{1}.series={s};tic;m2t2.ir.validate(ir);readSeconds=toc;tic;tex=m2t2.render.renderPgfplots(ir,true);renderSeconds=toc;bytes=numel(unicode2native(tex,'UTF-8'));m2t.internal.writeTextFile(fullfile(outputDirectory,'performance-10k.tex'),tex);fid=fopen(fullfile(outputDirectory,'performance.tsv'),'wb');cl=onCleanup(@()fclose(fid));fprintf(fid,'points\tir_seconds\trender_seconds\ttex_bytes\n%d\t%.6f\t%.6f\t%d\n',n,readSeconds,renderSeconds,bytes);clear cl;assert(bytes>n*10);d=sprintf('%d scalar-mapped points, IR %.3fs, TeX %.3fs, %d bytes',n,readSeconds,renderSeconds,bytes);end

    function writeTex(name,f),ir=m2t2.reader.readFigure(f);m2t.internal.writeTextFile(fullfile(outputDirectory,[name '.tex']),m2t2.render.renderPgfplots(ir,true));end
end

function [f,a,c,h]=figureWithScatter(sizeData,colorData,args),f=figure('Visible','off');c=onCleanup(@()closeFigure(f));a=axes('Parent',f);h=scatter(a,1:3,[2 1 3],sizeData,colorData,args{:});end
function s=readSeries(f),ir=m2t2.reader.readFigure(f);s=ir.axes{1}.series{1};end
function ir=scatterIr(colorMode,sizeMode),s=m2t2.ir.makeScatterSeries();s.x=[1 2 3];s.y=[2 1 3];s.color=[.2 .4 .8];s.edgeColor=s.color;if strcmp(sizeMode,'per_point'),s.sizeMode='per_point';s.markerSize=[4 6 10];end;if strcmp(colorMode,'per_point_rgb'),s.colorMode=colorMode;s.colorData=[1 0 0;0 1 0;0 0 1];s.edgeMode='data';elseif strcmp(colorMode,'scalar_mapped'),s.colorMode=colorMode;s.colorData=[10 20 30];s.edgeMode='none';s.faceMode='data';end;a=m2t2.ir.makeAxes();a.xlim=[0 4];a.ylim=[0 4];a.colorMapping.limits=[0 40];a.series={s};ir=m2t2.ir.makeFigure({a});ir.size=[100 65];end
function expect(fn,id),caught=false;try,fn();catch err,caught=strcmp(err.identifier,id);end;assert(caught);end
function writeRows(path,rows),fid=fopen(path,'wb');c=onCleanup(@()fclose(fid));fprintf(fid,'case\tstatus\tdetail\tlayer\n');for k=1:size(rows,1),fprintf(fid,'%s\t%s\t%s\t%s\n',rows{k,:});end;clear c;end
function value=identifier(err),value=err.identifier;if isempty(value),value='<none>';end,end
function value=oneLine(value),value=regexprep(value,'[\r\n\t]+',' ');end
function yes=has(value,fragment),yes=~isempty(strfind(value,fragment));end
function closeFigure(f),if ~isempty(f)&&ishandle(f),close(f);end,end
