function policy = defaultPolicy()
%DEFAULTPOLICY Return the deterministic M3.5 scalar-image planning policy.
    policy = struct('name', 'default', ...
                    'version', 1, ...
                    'maxVectorCells', 4096, ...
                    'id', 'default-v1');
end
