function fixtures = fixtureRegistry()
%FIXTUREREGISTRY Authoritative M4 cross-runtime semantic fixture matrix.
    rows = { ...
      'F01','line-basic','line','exact',true; ...
      'F02','multi-line','line','exact',false; ...
      'F03','scatter-basic','scatter','semantic',false; ...
      'F04','errorbar-symmetric','errorbar','semantic',true; ...
      'F05','errorbar-asymmetric','errorbar','semantic',false; ...
      'F06','line-scatter-mixed','line,scatter','semantic',false; ...
      'F07','line-errorbar-mixed','line,errorbar','semantic',false; ...
      'F08','legend','legend','semantic',true; ...
      'F09','custom-ticks','ticks','semantic',false; ...
      'F10','log-axes','axes','semantic',false; ...
      'F11','reverse-axes','axes','semantic',false; ...
      'F12','manual-axes-placement','layout','geometry',false; ...
      'F13','multiple-axes-1x2','layout','geometry',true; ...
      'F14','multiple-axes-2x2','layout','geometry',false; ...
      'F15','colorbar-vertical','colorbar','semantic',true; ...
      'F16','colorbar-horizontal','colorbar','semantic',false; ...
      'F17','shared-elements','shared-elements','runtime-constructible',false; ...
      'F18','imagesc-implicit','image','semantic',true; ...
      'F19','imagesc-explicit','image','semantic',false; ...
      'F20','imagesc-axis-xy','image','semantic',false; ...
      'F21','custom-clim','image','semantic',false; ...
      'F22','custom-colormap','image','semantic',true; ...
      'F23','publication-profile','profile','semantic',true; ...
      'F24','figure-set','set','semantic',false; ...
      'F25','hybrid-image','hybrid','semantic',true; ...
      'F26','auto-image-backend','planner','semantic',false};
    fixtures=repmat(struct('id','','name','','capabilities',{{}}, ...
        'expectedSupport','supported','visualReview',false,'comparisonMode',''),1,size(rows,1));
    for k=1:size(rows,1)
        fixtures(k)=struct('id',rows{k,1},'name',rows{k,2}, ...
            'capabilities',{strsplit(rows{k,3},',')},'expectedSupport','supported', ...
            'visualReview',rows{k,5},'comparisonMode',rows{k,4});
    end
end
