function layers = validationLayers()
%VALIDATIONLAYERS Return stable MATLAB validation layer definitions.
    ids = {'L0','L1','L2','L3','L4','L5','L6','L7','L8','L9','L10','L11'};
    names = {'Runtime/Environment','Reader Object Model','Normalized IR Semantics', ...
        'Renderer Determinism','TeX Compilation','Public m2t.export Workflow', ...
        'Publication Profile','Figure Sets','Image/Heatmap','Hybrid Backend', ...
        'Backend Planner','Legacy matlab2tikz smoke'};
    categories = {'ENV','HG','IR','RENDER','TEX','WORKFLOW','PROFILE','SET', ...
                  'IMAGE','HYBRID','PLANNER','LEGACY'};
    layers = repmat(struct('id','','name','','category',''),1,numel(ids));
    for k=1:numel(ids),layers(k)=struct('id',ids{k},'name',names{k},'category',categories{k});end
end
