function profile = publication()
%PUBLICATION Return the calibrated scientific-publication profile.
    texPointsPerMillimeter = 72.27 / 25.4;
    profile = struct();
    profile.name = 'publication';
    profile.enabled = true;
    profile.figure = struct( ...
        'defaultWidth', 'single-column', ...
        'widthNames', {{'single-column', 'double-column'}}, ...
        'widthMillimeters', [85 170], ...
        'widthTeXPoints', [85 170] * texPointsPerMillimeter, ...
        'minimumAspectRatio', 0.45, ...
        'maximumAspectRatio', 1.25, ...
        'standaloneBorderPt', 0);
    profile.axes = struct('preserveRelativePlacement', true);
    profile.text = struct( ...
        'basePt', 9, ...
        'axesLabelPt', 9, ...
        'titlePt', 10, ...
        'tickLabelPt', 8, ...
        'preserveInterpreter', true);
    profile.line = struct('widthPolicy', 'preserve', 'markerSizePolicy', 'preserve');
    profile.scatter = struct('markerSizePolicy', 'preserve');
    profile.legend = struct( ...
        'textPt', 8, ...
        'preserveOrder', true, ...
        'preserveOwnership', true, ...
        'preserveLocation', true);
    profile.colorbar = struct( ...
        'labelPt', 9, ...
        'tickLabelPt', 8, ...
        'preserveSemantics', true);
end
