function yes = isBoxplotObject(handle, axesHandle)
%ISBOXPLOTOBJECT Recognize MATLAB's semantic legacy-boxplot container.
    yes=false;
    try
        yes=strcmp(get(handle,'Type'),'hggroup') && ...
            strcmp(get(handle,'Tag'),'boxplot') && ...
            sameHandle(get(handle,'Parent'),axesHandle) && ...
            strcmp(getappdata(handle,'plottype'),'boxplot') && ...
            istable(getappdata(handle,'boxval')) && ...
            istable(getappdata(handle,'boxvalplot')) && ...
            isnumeric(getappdata(handle,'gpos')) && ...
            islogical(getappdata(handle,'notchon'));
    catch
        yes=false;
    end
end

function yes=sameHandle(a,b)
    try,v=a==b;yes=isscalar(v)&&logical(v);catch,yes=isequal(a,b);end
end
