function analysis = analyzeFigure(figureHandle)
%ANALYZEFIGURE Reuse the normalized reader/IR pipeline without writing files.
    analysis = struct('classification', 'invalid', 'ir', [], ...
                      'diagnostics', m2t.internal.emptyDiagnostics());
    try
        ir = m2t2.reader.readFigure(figureHandle);
        m2t2.ir.validate(ir);
        analysis.classification = 'supported';
        analysis.ir = ir;
    catch err
        if isUnsupported(err.identifier)
            analysis.classification = 'unsupported';
        end
        code = err.identifier;
        if isempty(code), code = 'M2T:E999:UnexpectedFailure'; end
        analysis.diagnostics(end + 1) = m2t.internal.makeDiagnostic( ...
            'error', code, err.message, 'analysis');
    end
end

function yes = isUnsupported(identifier)
    supported = {'M2T2:E001:UnsupportedObject', ...
                 'M2T2:E007:UnsupportedProperty', ...
                 'M2T2:E008:UnsupportedIRVersion', ...
                 'M2T2:E010:UnsupportedSharedLegend', ...
                 'M2T2:E011:UnsupportedColorbarOwnership', ...
                 'M2T2:E013:UnsupportedAnnotationType', ...
                 'M2T2:E014:UnsupportedAnnotationCoordinateSpace', ...
                 'M2T2:E015:UnsupportedAnnotationInterpreter', ...
                 'M2T2:E017:UnsupportedAnnotationOwnership', ...
                 'M2T2:E018:UnsupportedBarMode', ...
                 'M2T2:E019:UnsupportedBarOrientation', ...
                 'M2T2:E020:UnsupportedBarCategory', ...
                 'M2T2:E021:UnsupportedBarColorMode', ...
                 'M2T2:E023:AmbiguousBarOwnership', ...
                 'M2T2:E024:UnsupportedBoxplotOrientation', ...
                 'M2T2:E025:UnsupportedBoxplotVariant', ...
                 'M2T2:E026:UnsupportedBoxplotStyle', ...
                 'M2T2:E028:AmbiguousBoxplotCompound', ...
                 'M2T2:E029:UnsupportedBoxplotNotch', ...
                 'M2T2:E030:UnsupportedBoxplotGrouping', ...
                 'M2T2:E031:Unsupported3DPrimitive', ...
                 'M2T2:E032:Unsupported3DProjection', ...
                 'M2T2:E033:UnsupportedSurfaceGeometry', ...
                 'M2T2:E033:UnsupportedSurfaceEdgeMode', ...
                 'M2T2:E034:UnsupportedSurfaceColorMode', ...
                 'M2T2:E035:UnsupportedSurfaceTransparency', ...
                 'M2T2:E036:UnsupportedLighting', ...
                 'M2T2:E037:Unsupported3DPatchVariant', ...
                 'M2T2:E038:Malformed3DData', ...
                 'M2T2:E039:Unsupported3DAxesFeature', ...
                 'M2T2:E_IMAGE_RGB_UNSUPPORTED', ...
                 'M2T2:E_IMAGE_ALPHA_UNSUPPORTED', ...
                 'M2T2:E_IMAGE_DIMENSIONS_INVALID', ...
                 'M2T2:E_IMAGE_COORDINATES_UNSUPPORTED', ...
                 'M2T2:E_IMAGE_MAPPING_UNSUPPORTED', ...
                 'M2T2:E_IMAGE_NONFINITE_UNSUPPORTED'};
    yes = any(strcmp(identifier, supported));
end
