function result = emptyExportResult()
%EMPTYEXPORTRESULT Return the stable single-figure workflow result shape.
    result = struct( ...
        'success', false, ...
        'status', 'export_failed', ...
        'capability', 'invalid', ...
        'texPath', '', ...
        'pdfPath', '', ...
        'logPath', '', ...
        'backend', 'pgfplots', ...
        'render', struct('requestedImageBackend', 'vector', ...
                         'effectiveImageBackend', 'vector', ...
                         'imageBackend', struct( ...
                             'requested', 'vector', 'selected', 'vector', ...
                             'reason', 'not_planned', ...
                             'policy', m2t.planning.defaultPolicy(), ...
                             'imageLayerCount', 0, 'maxImageCells', 0), ...
                         'assets', {cell(1, 0)}), ...
        'compiler', 'lualatex', ...
        'profile', struct('name', 'none', 'width', 'source', ...
                          'widthMillimeters', [], 'figureSize', [], ...
                          'figureSizeUnit', 'pt'), ...
        'diagnostics', m2t.internal.emptyDiagnostics(), ...
        'timings', struct('analysis', 0, 'export', 0, 'compile', 0, ...
                          'validation', 0, 'total', 0));
end
